### ISSUE TITLE
Missing comparison.nf in the repo?

### ISSUE THREAD

**Issue by tonyliang19** [DabinJeong/Comparative_analysis_multi-omics_biomarker#1]
Hello, I was trying to clone your repo and run the Nextflow script with the following snippet:
```bash
nextflow run comparison.nf -c comparison.config -with-docker biomarker_comparison:0.1.1
```
However, I could not seem to find the `comparison.nf` file, not in any of the current or previous commits. Is it possible to have access to it? Thanks

**Comment by DabinJeong** [comment]
Sorry for inconvenience. I have uploaded `comparison.nf` file. Please check out the file and let me know if there is any other issue.
Thanks.

**Comment by tonyliang19** [comment]
Thanks!
